// Generated by CoffeeScript 1.7.1
(function() {
  var fs, path, readability, should;

  readability = require("../lib/index");

  should = require("should");

  path = require("path");

  fs = require("fs");

  describe("grab article test", function() {
    return it("case 2", function(done) {
      var sample2Path;
      sample2Path = path.join(__dirname, "/samples/2.html");
      return fs.readFile(sample2Path, function(err, data) {
        var article;
        should(err).be.empty;
        readability = new readability({
          content: data.toString()
        });
        article = readability.grabArticle();
        should(article).not.be.empty;
        article.text.should.not.be.empty;
        console.dir(article);
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=grabarticle.test.map
