// Generated by CoffeeScript 1.7.1
(function() {
  var fs, path, readability, should;

  readability = require("../lib/index");

  should = require("should");

  path = require("path");

  fs = require("fs");

  describe("grab article test", function() {
    it("case 1", function(done) {
      var sample1Path;
      done();
      return;
      sample1Path = path.join(__dirname, "/samples/1.html");
      return fs.readFile(sample1Path, function(err, data) {
        var article, read;
        should(err).be.empty;
        read = new readability({
          content: data.toString()
        });
        article = read.run();
        article.text.should.not.be.empty;
        return done();
      });
    });
    it("case 2", function(done) {
      var sample2Path;
      done();
      return;
      sample2Path = path.join(__dirname, "/samples/2.html");
      return fs.readFile(sample2Path, function(err, data) {
        var article, read;
        should(err).be.empty;
        read = new readability({
          content: data.toString()
        });
        article = read.run();
        should(article).not.be.empty;
        article.text.should.not.be.empty;
        return done();
      });
    });
    return it("case 3", function(done) {
      var sample3Path;
      done();
      return;
      sample3Path = path.join(__dirname, "/samples/3.html");
      return fs.readFile(sample3Path, function(err, data) {
        var article, read;
        should(err).be.empty;
        read = new readability({
          content: data.toString()
        });
        article = read.run();
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=grabarticle.test.map
