// Generated by CoffeeScript 1.7.1
(function() {
  var $, should, util;

  should = require("should");

  $ = require("cheerio");

  util = require("../lib/util");

  describe("util test", function() {
    return describe("remove single header test", function() {
      it("should be empty after remove", function() {
        var html, obj;
        html = "<div><h5>test header</h5></div>";
        obj = $("div", html);
        util.removeSingleHeader(obj);
        return obj.html().should.be.empty;
      });
      return it("should remain a div and h5 which have sibling", function() {
        var html, obj;
        html = "<div><div><h3>test</h3></div><h5>should remain</h5></div>";
        obj = $(html);
        util.removeSingleHeader(obj);
        return obj.html().should.be.exactly("<div></div><h5>should remain</h5>");
      });
    });
  });

}).call(this);

//# sourceMappingURL=util.test.map
